### PR TITLE
unhandled_keypress: fix inconsistent behaviour of ctrl/meta right

### LINKED ISSUE #24: Ctrl+Right won't jump to the end of a line
But Ctrl+Left to go left 1 word does go left 1 word like it should.  Not sure I can fix this but I can try.

https://github.com/scopatz/xo/blob/febf634fb6f2988f22aed987301c1c349e4b2a98/xo.py#L856-L862

### PR DESCRIPTION
**Pull request by catb0t**
this changed the `ctrl/meta right` behaviour to be consistent with `ctrl/meta left`

also mark xo.py executable for convenience

close #24

### CODE REVIEW

**Comment by scopatz** [comment]
Ahh good catch, thanks! Also can you add a news entry. There are instructions here: https://regro.github.io/rever-docs/news.html

**Comment by catb0t** [comment]
Does that include incrementing the version number?

**Comment by catb0t** [comment]
Sorry that took so long, I was trying to wrap my head around those instructions. I think I've got it right now?

**Comment by scopatz** [comment]
Yes, this is great! Sorry if the instructions were confusing!

**Pull request merged**
